Jenkins Pipeline Demo

diff --git a/Spring-boot-jenkins-demo/Jenkinfile b/Spring-boot-jenkins-demo/Jenkinfile
--- a/Spring-boot-jenkins-demo/Jenkinfile
+++ b/Spring-boot-jenkins-demo/Jenkinfile
@@ -1,30 +1,55 @@
 pipeline {
     agent any
     environment {
-        userName="Narendran"
+        version="1.1"
         checkoutBranch="main"
     }
 
     stages {
+
+		stage("audit") {
+			parallel {
+                stage('audit-java') {
+                    steps {
+                        bat '''
+                            java --version
+                        '''
+                    }
+                }
+                stage('audit-git-mvn') {
+                    steps {
+                        bat '''
+                            git --version
+                            mvn --version
+                        '''
+                    }
+                }
+            }
+		}
+
         stage("checkout") {
             steps {
                 script {
                     def gitRepoUrl = "https://github.com/Narendran3678/Jenkins-Hub.git"
                     checkout([$class: 'GitSCM',
-                        branches: [[name: '*/main']],
+                        branches: [[name: "*/${checkoutBranch}"]],
                         userRemoteConfigs: [[url: gitRepoUrl]],
-                        extensions: [[$class: 'CleanBeforeCheckout'], [$class: 'CloneOption', noTags: false, shallow: true, depth: 1]]
+                        extensions: [
+                            [$class: 'CleanBeforeCheckout'],
+                            [$class: 'CloneOption', noTags: false, shallow: true, depth: 1]
+                        ]
                     ])
                 }
             }
         }
 
         stage("Build") {
+
             steps {
                 echo "############################# Build Stage Started ###############################"
-                 bat '''
+                bat '''
                 cd Spring-boot-jenkins-demo
-                mvn clean install -DskipTests=true
+                mvn clean install -DskipTests=true versions:set -DnewVersion='%version%' versions:update-child-modules
                 '''
                 echo "############################# Build Stage Completed #############################"
             }
@@ -66,7 +91,7 @@ pipeline {
             echo "Archiving Jar Files."
         }
         failure {
-            echo "Checkout Failed for User $userName"
+            echo "PreProcess Failed"
         }
     }
 }
